configure.ac: add --with-pcrecpp.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -748,23 +748,28 @@ PKG_CONFIG
 libcurl_CFLAGS
 libcurl_LIBS
 LIBOBJS
-WITH_MAN_TRUE
-WITH_MAN_FALSE
 ENABLE_TESTS_TRUE
 ENABLE_TESTS_FALSE
 libiconv_CFLAGS
-libiconv_LDFLAGS
+libiconv_LIBS
 WITH_ICONV_TRUE
 WITH_ICONV_FALSE
+libpcrecpp_CFLAGS
+libpcrecpp_LIBS
+WITH_PCRE_TRUE
+WITH_PCRE_FALSE
+WITH_MAN_TRUE
+WITH_MAN_FALSE
 LTLIBOBJS'
 ac_subst_files=''
 ac_user_opts='
 enable_option_checking
 enable_dependency_tracking
-with_man
 enable_sigwinch
 enable_tests
 with_iconv
+with_pcrecpp
+with_man
 '
       ac_precious_vars='build_alias
 host_alias
@@ -780,7 +785,9 @@ CFLAGS
 CPP
 PKG_CONFIG
 libcurl_CFLAGS
-libcurl_LIBS'
+libcurl_LIBS
+libpcrecpp_CFLAGS
+libpcrecpp_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1420,8 +1427,10 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-iconv=PREFIX     search for libiconv in PREFIX [default=/usr]
+  --with-pcrecpp=PREFIX   search for libpcrecpp in PREFIX [default=pkg-config
+                          returned path]
   --with-man              install cclive.1 manual page [default=yes]
-  --with-iconv=prefix     build with libiconv [default=no]
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -1439,6 +1448,10 @@ Some influential environment variables:
               C compiler flags for libcurl, overriding pkg-config
   libcurl_LIBS
               linker flags for libcurl, overriding pkg-config
+  libpcrecpp_CFLAGS
+              C compiler flags for libpcrecpp, overriding pkg-config
+  libpcrecpp_LIBS
+              linker flags for libpcrecpp, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -5161,7 +5174,7 @@ fi
 
 
 
-# Checks for libraries.
+# Checks for (mandatory) libraries.
 
 
 if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
@@ -7219,24 +7232,6 @@ fi
 done
 
 
-# --with-man
-
-# Check whether --with-man was given.
-if test "${with_man+set}" = set; then
-  withval=$with_man;
-else
-  with_man=yes
-fi
-
- if test x"$with_man" != "xno"; then
-  WITH_MAN_TRUE=
-  WITH_MAN_FALSE='#'
-else
-  WITH_MAN_TRUE='#'
-  WITH_MAN_FALSE=
-fi
-
-
 # --enable-sigwinch
 # Check whether --enable-sigwinch was given.
 if test "${enable_sigwinch+set}" = set; then
@@ -7476,7 +7471,7 @@ fi
 { $as_echo "$as_me:$LINENO: result: $ac_cv_lib_iconv_iconv_open" >&5
 $as_echo "$ac_cv_lib_iconv_iconv_open" >&6; }
 if test $ac_cv_lib_iconv_iconv_open = yes; then
-  libiconv_LDFLAGS=-liconv
+  libiconv_LIBS=-liconv
 fi
 
 
@@ -7484,11 +7479,11 @@ fi
 
 
     else
-        # Use the user supplied prefix instead. Presume s/he knows better.
+        # User knows better.
         libiconv_CFLAGS="-I$with_iconv/include"
-        libiconv_LDFLAGS="-L$with_iconv/lib -liconv"
+        libiconv_LIBS="-L$with_iconv/lib -liconv"
     fi
-    if  test x"$libiconv_LDFLAGS" = "x" ; then
+    if  test x"$libiconv_LIBS" = "x" ; then
         { { $as_echo "$as_me:$LINENO: error: libiconv not found" >&5
 $as_echo "$as_me: error: libiconv not found" >&2;}
    { (exit 1); exit 1; }; }
@@ -7507,6 +7502,169 @@ fi
 else
   WITH_ICONV_TRUE='#'
   WITH_ICONV_FALSE=
+fi
+
+
+
+# Check whether --with-pcrecpp was given.
+if test "${with_pcrecpp+set}" = set; then
+  withval=$with_pcrecpp; with_pcrecpp=$withval
+else
+  with_pcrecpp=no
+
+fi
+
+if  test x"$with_pcrecpp" != "xno" ; then
+    if  test x"$with_pcrecpp" = "xyes" ; then
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for libpcrecpp" >&5
+$as_echo_n "checking for libpcrecpp... " >&6; }
+
+if test -n "$libpcrecpp_CFLAGS"; then
+    pkg_cv_libpcrecpp_CFLAGS="$libpcrecpp_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libpcrecpp >= 7.9\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libpcrecpp >= 7.9") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_libpcrecpp_CFLAGS=`$PKG_CONFIG --cflags "libpcrecpp >= 7.9" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$libpcrecpp_LIBS"; then
+    pkg_cv_libpcrecpp_LIBS="$libpcrecpp_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libpcrecpp >= 7.9\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libpcrecpp >= 7.9") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_libpcrecpp_LIBS=`$PKG_CONFIG --libs "libpcrecpp >= 7.9" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        libpcrecpp_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libpcrecpp >= 7.9" 2>&1`
+        else
+	        libpcrecpp_PKG_ERRORS=`$PKG_CONFIG --print-errors "libpcrecpp >= 7.9" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$libpcrecpp_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (libpcrecpp >= 7.9) were not met:
+
+$libpcrecpp_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables libpcrecpp_CFLAGS
+and libpcrecpp_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements (libpcrecpp >= 7.9) were not met:
+
+$libpcrecpp_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables libpcrecpp_CFLAGS
+and libpcrecpp_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables libpcrecpp_CFLAGS
+and libpcrecpp_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables libpcrecpp_CFLAGS
+and libpcrecpp_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	libpcrecpp_CFLAGS=$pkg_cv_libpcrecpp_CFLAGS
+	libpcrecpp_LIBS=$pkg_cv_libpcrecpp_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+    else
+        # User knows better.
+        libpcrecpp_CFLAGS="-I$with_pcrecpp/include"
+        libpcrecpp_LIBS="-L$with_pcrecpp/lib -lpcrecpp"
+    fi
+    if  test x"$libpcrecpp_LIBS" = "x" ; then
+        { { $as_echo "$as_me:$LINENO: error: libpcrecpp not found" >&5
+$as_echo "$as_me: error: libpcrecpp not found" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+
+
+cat >>confdefs.h <<\_ACEOF
+#define WITH_PCRE 1
+_ACEOF
+
+fi
+ if test x"$with_pcre" != "xno"; then
+  WITH_PCRE_TRUE=
+  WITH_PCRE_FALSE='#'
+else
+  WITH_PCRE_TRUE='#'
+  WITH_PCRE_FALSE=
+fi
+
+
+# --with-man
+
+# Check whether --with-man was given.
+if test "${with_man+set}" = set; then
+  withval=$with_man;
+else
+  with_man=yes
+fi
+
+ if test x"$with_man" != "xno"; then
+  WITH_MAN_TRUE=
+  WITH_MAN_FALSE='#'
+else
+  WITH_MAN_TRUE='#'
+  WITH_MAN_FALSE=
 fi
 
 
@@ -8173,13 +8331,6 @@ $as_echo "$as_me: error: conditional \"HAVE_POD2HTML\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${WITH_MAN_TRUE}" && test -z "${WITH_MAN_FALSE}"; then
-  { { $as_echo "$as_me:$LINENO: error: conditional \"WITH_MAN\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-$as_echo "$as_me: error: conditional \"WITH_MAN\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${ENABLE_TESTS_TRUE}" && test -z "${ENABLE_TESTS_FALSE}"; then
   { { $as_echo "$as_me:$LINENO: error: conditional \"ENABLE_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -8191,6 +8342,20 @@ if test -z "${WITH_ICONV_TRUE}" && test -z "${WITH_ICONV_FALSE}"; then
   { { $as_echo "$as_me:$LINENO: error: conditional \"WITH_ICONV\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 $as_echo "$as_me: error: conditional \"WITH_ICONV\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WITH_PCRE_TRUE}" && test -z "${WITH_PCRE_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"WITH_PCRE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"WITH_PCRE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WITH_MAN_TRUE}" && test -z "${WITH_MAN_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"WITH_MAN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"WITH_MAN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
