Make pcre mandatory. Remove --with-pcrecpp.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -749,13 +749,11 @@ HAVE_POD2HTML_FALSE
 PKG_CONFIG
 libcurl_CFLAGS
 libcurl_LIBS
+libpcrecpp_CFLAGS
+libpcrecpp_LIBS
 LIBOBJS
 ENABLE_TESTS_TRUE
 ENABLE_TESTS_FALSE
-libpcrecpp_CFLAGS
-libpcrecpp_LIBS
-WITH_PCRE_TRUE
-WITH_PCRE_FALSE
 WITH_MAN_TRUE
 WITH_MAN_FALSE
 LTLIBOBJS'
@@ -768,7 +766,6 @@ enable_rpath
 with_libiconv_prefix
 enable_sigwinch
 enable_tests
-with_pcrecpp
 with_man
 '
       ac_precious_vars='build_alias
@@ -1431,8 +1428,6 @@ Optional Packages:
   --with-gnu-ld           assume the C compiler uses GNU ld default=no
   --with-libiconv-prefix[=DIR]  search for libiconv in DIR/include and DIR/lib
   --without-libiconv-prefix     don't search for libiconv in includedir and libdir
-  --with-pcrecpp=PREFIX   search for libpcrecpp in PREFIX [default=pkg-config
-                          returned path]
   --with-man              install cclive.1 manual page [default=yes]
 
 Some influential environment variables:
@@ -6403,6 +6398,113 @@ $as_echo "yes" >&6; }
 	:
 fi
 
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for libpcrecpp" >&5
+$as_echo_n "checking for libpcrecpp... " >&6; }
+
+if test -n "$libpcrecpp_CFLAGS"; then
+    pkg_cv_libpcrecpp_CFLAGS="$libpcrecpp_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libpcrecpp >= 7.8\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libpcrecpp >= 7.8") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_libpcrecpp_CFLAGS=`$PKG_CONFIG --cflags "libpcrecpp >= 7.8" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$libpcrecpp_LIBS"; then
+    pkg_cv_libpcrecpp_LIBS="$libpcrecpp_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libpcrecpp >= 7.8\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libpcrecpp >= 7.8") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_libpcrecpp_LIBS=`$PKG_CONFIG --libs "libpcrecpp >= 7.8" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        libpcrecpp_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libpcrecpp >= 7.8" 2>&1`
+        else
+	        libpcrecpp_PKG_ERRORS=`$PKG_CONFIG --print-errors "libpcrecpp >= 7.8" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$libpcrecpp_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (libpcrecpp >= 7.8) were not met:
+
+$libpcrecpp_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables libpcrecpp_CFLAGS
+and libpcrecpp_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements (libpcrecpp >= 7.8) were not met:
+
+$libpcrecpp_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables libpcrecpp_CFLAGS
+and libpcrecpp_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables libpcrecpp_CFLAGS
+and libpcrecpp_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables libpcrecpp_CFLAGS
+and libpcrecpp_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	libpcrecpp_CFLAGS=$pkg_cv_libpcrecpp_CFLAGS
+	libpcrecpp_LIBS=$pkg_cv_libpcrecpp_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+
 # Checks for header files.
 { $as_echo "$as_me:$LINENO: checking for ANSI C header files" >&5
 $as_echo_n "checking for ANSI C header files... " >&6; }
@@ -8265,152 +8367,6 @@ else
 fi
 
 
-# --with-pcrecpp
-
-# Check whether --with-pcrecpp was given.
-if test "${with_pcrecpp+set}" = set; then
-  withval=$with_pcrecpp; with_pcrecpp=$withval
-else
-  with_pcrecpp=no
-
-fi
-
-if  test x"$with_pcrecpp" != "xno" ; then
-    if  test x"$with_pcrecpp" = "xyes" ; then
-
-pkg_failed=no
-{ $as_echo "$as_me:$LINENO: checking for libpcrecpp" >&5
-$as_echo_n "checking for libpcrecpp... " >&6; }
-
-if test -n "$libpcrecpp_CFLAGS"; then
-    pkg_cv_libpcrecpp_CFLAGS="$libpcrecpp_CFLAGS"
- elif test -n "$PKG_CONFIG"; then
-    if test -n "$PKG_CONFIG" && \
-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libpcrecpp >= 7.8\"") >&5
-  ($PKG_CONFIG --exists --print-errors "libpcrecpp >= 7.8") 2>&5
-  ac_status=$?
-  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; then
-  pkg_cv_libpcrecpp_CFLAGS=`$PKG_CONFIG --cflags "libpcrecpp >= 7.8" 2>/dev/null`
-else
-  pkg_failed=yes
-fi
- else
-    pkg_failed=untried
-fi
-if test -n "$libpcrecpp_LIBS"; then
-    pkg_cv_libpcrecpp_LIBS="$libpcrecpp_LIBS"
- elif test -n "$PKG_CONFIG"; then
-    if test -n "$PKG_CONFIG" && \
-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libpcrecpp >= 7.8\"") >&5
-  ($PKG_CONFIG --exists --print-errors "libpcrecpp >= 7.8") 2>&5
-  ac_status=$?
-  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; then
-  pkg_cv_libpcrecpp_LIBS=`$PKG_CONFIG --libs "libpcrecpp >= 7.8" 2>/dev/null`
-else
-  pkg_failed=yes
-fi
- else
-    pkg_failed=untried
-fi
-
-
-
-if test $pkg_failed = yes; then
-
-if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
-        _pkg_short_errors_supported=yes
-else
-        _pkg_short_errors_supported=no
-fi
-        if test $_pkg_short_errors_supported = yes; then
-	        libpcrecpp_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libpcrecpp >= 7.8" 2>&1`
-        else
-	        libpcrecpp_PKG_ERRORS=`$PKG_CONFIG --print-errors "libpcrecpp >= 7.8" 2>&1`
-        fi
-	# Put the nasty error message in config.log where it belongs
-	echo "$libpcrecpp_PKG_ERRORS" >&5
-
-	{ { $as_echo "$as_me:$LINENO: error: Package requirements (libpcrecpp >= 7.8) were not met:
-
-$libpcrecpp_PKG_ERRORS
-
-Consider adjusting the PKG_CONFIG_PATH environment variable if you
-installed software in a non-standard prefix.
-
-Alternatively, you may set the environment variables libpcrecpp_CFLAGS
-and libpcrecpp_LIBS to avoid the need to call pkg-config.
-See the pkg-config man page for more details.
-" >&5
-$as_echo "$as_me: error: Package requirements (libpcrecpp >= 7.8) were not met:
-
-$libpcrecpp_PKG_ERRORS
-
-Consider adjusting the PKG_CONFIG_PATH environment variable if you
-installed software in a non-standard prefix.
-
-Alternatively, you may set the environment variables libpcrecpp_CFLAGS
-and libpcrecpp_LIBS to avoid the need to call pkg-config.
-See the pkg-config man page for more details.
-" >&2;}
-   { (exit 1); exit 1; }; }
-elif test $pkg_failed = untried; then
-	{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
-is in your PATH or set the PKG_CONFIG environment variable to the full
-path to pkg-config.
-
-Alternatively, you may set the environment variables libpcrecpp_CFLAGS
-and libpcrecpp_LIBS to avoid the need to call pkg-config.
-See the pkg-config man page for more details.
-
-To get pkg-config, see <http://pkg-config.freedesktop.org/>.
-See \`config.log' for more details." >&5
-$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
-is in your PATH or set the PKG_CONFIG environment variable to the full
-path to pkg-config.
-
-Alternatively, you may set the environment variables libpcrecpp_CFLAGS
-and libpcrecpp_LIBS to avoid the need to call pkg-config.
-See the pkg-config man page for more details.
-
-To get pkg-config, see <http://pkg-config.freedesktop.org/>.
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
-else
-	libpcrecpp_CFLAGS=$pkg_cv_libpcrecpp_CFLAGS
-	libpcrecpp_LIBS=$pkg_cv_libpcrecpp_LIBS
-        { $as_echo "$as_me:$LINENO: result: yes" >&5
-$as_echo "yes" >&6; }
-	:
-fi
-    else
-        # User knows better.
-        libpcrecpp_CFLAGS="-I$with_pcrecpp/include"
-        libpcrecpp_LIBS="-L$with_pcrecpp/lib -lpcrecpp"
-    fi
-    if  test x"$libpcrecpp_LIBS" = "x" ; then
-        { { $as_echo "$as_me:$LINENO: error: libpcrecpp not found" >&5
-$as_echo "$as_me: error: libpcrecpp not found" >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-
-
-
-cat >>confdefs.h <<\_ACEOF
-#define WITH_PCRE 1
-_ACEOF
-
-fi
- if test x"$with_pcre" != "xno"; then
-  WITH_PCRE_TRUE=
-  WITH_PCRE_FALSE='#'
-else
-  WITH_PCRE_TRUE='#'
-  WITH_PCRE_FALSE=
-fi
-
-
 # --with-man
 
 # Check whether --with-man was given.
@@ -9071,13 +9027,6 @@ if test -z "${ENABLE_TESTS_TRUE}" && test -z "${ENABLE_TESTS_FALSE}"; then
   { { $as_echo "$as_me:$LINENO: error: conditional \"ENABLE_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 $as_echo "$as_me: error: conditional \"ENABLE_TESTS\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test -z "${WITH_PCRE_TRUE}" && test -z "${WITH_PCRE_FALSE}"; then
-  { { $as_echo "$as_me:$LINENO: error: conditional \"WITH_PCRE\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-$as_echo "$as_me: error: conditional \"WITH_PCRE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
